
title: Qlack
description: Qlack combines a variety of technologies in a cutting-edge technological stack totally based on Open
        Source Software.
        Qlack allows applications to fully empower a Rapid Application Development (RAD) approach as it provides most
        of the bread and butter functionality needed in the majority applications of today.
        A variety of more than 25 different modules, self-packed and with no interdependencies between them, with full
        unit tests and a benchmark suite allowing to evaluate Qlack modules on your own hardware and application setup
        is available.


baseurl: "" 
url: "https://qlack.github.io"

markdown: kramdown

theme: minima
plugins:
  - jekyll-feed

